# To use:
  # $ conda env create -f environment.yml
  # $ conda activate cv
name: ContinuousBlackjack
dependencies:
  - python
  - pip
  - pip:
    - ipykernel
    - numpy
    - pandas
    - torch
    - seaborn
    - matplotlib
    - scipy
    - cython
